before:
  hooks:
    - go mod tidy

# --ldflags "-s -w -X main.version=${version} -X main.gitHash=${githash} -X main.binaryName=certsync_client" \
builds:
  - id: server
    main: ./server
    binary: certsync_server
    ldflags:
    - -s
    - -w 
    - -X main.version={{.Version}}
    - -X main.gitCommit={{.ShortCommit}}
    - -X main.binaryName={{.Binary}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
  - id: client
    main: ./client
    binary: certsync_client
    ldflags:
    - -s
    - -w 
    - -X main.version={{.Version}}
    - -X main.gitCommit={{.ShortCommit}}
    - -X main.binaryName={{.Binary}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
archives:
  - id: server
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - server
    format_overrides:
      - goos: windows
        format: zip
  - id: client
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - client
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

announce:
  skip: "true"