before:
  hooks:
    - go mod tidy

builds:
  - id: server
    main: ./server
    binary: certsync_server
    ldflags:
    - -s
    - -w 
    - -X main.version={{.Version}}
    - -X main.gitCommit={{.ShortCommit}}
    - -X main.binaryName={{.Binary}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
  - id: client
    main: ./client
    binary: certsync_client
    ldflags:
    - -s
    - -w 
    - -X main.version={{.Version}}
    - -X main.gitCommit={{.ShortCommit}}
    - -X main.binaryName={{.Binary}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64

archives:
  - id: server
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - server
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      arm: armhf
  
  - id: client
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - client
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      arm: armhf
  
nfpms:
  - id: server
    maintainer: "Marko Milivojevic <markom@gmail.com>"
    package_name: certsync_server
    description: "CertSync server. See: https://github.com/icemarkom/certsync"
    bindir: /usr/local/sbin
    builds:
      - server
    formats:
      - apk
      - deb
      - rpm
    replacements:
      arm: armhf
  - id: client
    maintainer: "Marko Milivojevic <markom@gmail.com>"
    package_name: certsync_client
    description: "CertSync client. See: https://github.com/icemarkom/certsync"
    bindir: /usr/local/bin
    builds:
      - client
    formats:
      - apk
      - deb
      - rpm
    replacements:
      arm: armhf

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

announce:
  skip: "true"
